### PR TITLE
Add the missing gradle config files.

### PR DESCRIPTION
**Pull request by UglyTroLL**
So that others can import this project from IDE, and make them to contribute to this project easier.
Without those files, the current version cannot be imported from any IDE directly from a fresh check out.

### CODE REVIEW

**Comment by theDazzler** [comment]
@UglyTroLL I added the files back in. You should be able to import now. Let me know if you have any issues

**Comment by UglyTroLL** [comment]
Cool, thanks! But I believe the '.gradle/*' (which was checked in in your last commit) shouldn't be there

**Comment by theDazzler** [comment]
Where do you see that at? I checked my last commit and don't see it

**Comment by UglyTroLL** [comment]
@theDazzler Sorry, from this commit : https://github.com/theDazzler/droidicon/commit/ae412cee5e01ac460cc6c8f3e42d1fa4f2dd9182

**Comment by theDazzler** [comment]
@UglyTroLL ok yea you are correct. I removed it. Thanks a lot!

**Pull request closed without merging**
