### PR TITLE
Allow users to add their own icon sets in run-time

### PR DESCRIPTION
**Pull request by UglyTroLL**
Allow users to add their own icon sets (and use them) in run-time, instead of limiting the icon sets to the provided ones.

### CODE REVIEW

**Comment by UglyTroLL** [comment]
Hi @theDazzler,
This one may look like a huge change but it's not that complicated.
1. Replace the typeface enums with custom singleton classes to make it possible to expand the icon sets. Also, decoupling the iconMap/resourceId for each typeface makes it easier to update (instead of having a huge map for all of them).
2. I also added the sample to the test app to include both unicode and custom fonts usages.

**Comment by theDazzler** [comment]
@UglyTroLL ill try to check out your pull request this weekend

**Comment by UglyTroLL** [comment]
Sure! Let me know if there is any problems.

**Comment by UglyTroLL** [comment]
Hi @theDazzler , just want to check if you have any questions/problems with this PR. 
I will sync with you before I want to make any big changes on this repo to check if you are fine with them.
I'm also planning to extend this library to Text so that the icons can be rendered in any TextView, but I probably need this PR to be merged before I can start working on that.

**Comment by theDazzler** [comment]
@UglyTroLL Sorry for the delay. I get merge conflicts when trying to checkout your pull request. Can you fix them so I can test?

**Comment by UglyTroLL** [comment]
@theDazzler Yes, it's weird, the merge conflicts are mainly in the sample app, but I have no idea why did it happen. Let me try to merge the upstream tomorrow and commit a non-conflict (hopefully) PR.

**Comment by theDazzler** [comment]
@UglyTroLL ok cool. I have tested your pull a request a little bit, I like it. The only issue is that I am getting the error "cannot find symbol IconicFontDrawable" inside Android Studio. I am trying to figure out what exactly is causing it because I don't get that error in the master branch. It seems to still compile even though there is that error.

**Comment by theDazzler** [comment]
@UglyTroLL Okay nevermind. I fixed the error. It was on my end.

**Comment by UglyTroLL** [comment]
@theDazzler I've merged the upstream and now it looks good to go.

**Pull request merged**
